name: sdc_decal
dependencies:
    - python=3.6
    - pyzmq
    - numpy
    - pyyaml=3.12
    - pip
    - scikit-learn
    - matplotlib
    - pip:
        - gym
        - pyglet
        - opencv-python
        - scikit-image
        - dataclasses
        - pygeometry
        - cloudpickle
        - torch
        - torchvision
        - jupyter
